theme: minima
title: Chronicles of the World
author: Matthew Otto
description: A site made to play an evergrowing text-based adventure.
permalink: /:categories/:year/:month/:day/:title:output_ext
